package controlador;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;
import utilidades.ConexionDB;

/**
 *
 * @author Quique
 */
public class Pedidos extends javax.swing.JFrame {
    
    Connection conex = new ConexionDB().getCon(); //OBTENGO LA CONEXION QUE CREO EN OTRO PAQUETE
   
    DefaultTableModel model;    
    Statement s;
    ResultSet rs;
    int x, y; //VARIABLES USADAS PARA EL MARCO DEL FRAME, PARA MOVERLO
    
    int viewRow, modelRow;    
    
    /**
     * Creates new form Pedidos
     */
    public Pedidos() throws SQLException, ClassNotFoundException {
        initComponents();
        this.setLocationRelativeTo(null);  
        //AWTUtilities.setWindowOpaque(this, false);//PARA EL MARCO MOVER FRAME
        this.model = (DefaultTableModel) jTable1.getModel();        
        //SETEA EL ANCHO DE LAS COLUMNAS      
        TableColumnModel columnModel = jTable1.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(45);
        columnModel.getColumn(1).setPreferredWidth(200);
        columnModel.getColumn(2).setPreferredWidth(180);
        columnModel.getColumn(3).setPreferredWidth(65);
        columnModel.getColumn(4).setPreferredWidth(150);
        
        statusText.setVisible(false);
        
        //LLENA LA TABLA
        String query = "SELECT * FROM pedidos";
        PreparedStatement ps = conex.prepareStatement(query);
        ResultSet rs = ps.executeQuery();
        
        Object datosFila[] = new Object[5];

        while(rs.next()) {
            datosFila[0] = Integer.parseInt(rs.getString("id"));
            datosFila[1] = rs.getString("fecha");
            datosFila[2] = getNombreArticulo(Integer.parseInt(rs.getString("articulo")));
            datosFila[3] = getValorTalla(Integer.parseInt(rs.getString("talla")));
            datosFila[4] = rs.getString("estado");

            model.addRow(datosFila);
        }        
        
        jTable1.addMouseListener(new MouseAdapter() { //CREA UN LISTENER PARA EL RATÓN

            @Override
            public void mouseClicked(MouseEvent e) { //CUANDO SELECCIONAS UNA FILA DE LA TABLA, SETEA LOS jTextField PARA EDITARLOS              
                if (jTFBuscarPedidos.getText().isEmpty()) {
                    int i = jTable1.getSelectedRow();
                    // 'i' HACE REFERENCIA AL NÚMERO DE LA FILA SELECCIONADA Y EL NÚMERO HACE REFERENCIA A LA COLUMNA (i,n)
                    TFID.setText(model.getValueAt(i, 0).toString());
                    TFFecha.setText(model.getValueAt(i, 1).toString());
                    TFArticulo.setText(model.getValueAt(i, 2).toString());
                    TFTalla.setText(model.getValueAt(i, 3).toString());
                    TFEstado.setText(model.getValueAt(i, 4).toString());
                } else {
                    int i = modelRow;
                    TFID.setText(model.getValueAt(i, 0).toString());
                    TFFecha.setText(model.getValueAt(i, 1).toString());
                    TFArticulo.setText(model.getValueAt(i, 2).toString());
                    TFTalla.setText(model.getValueAt(i, 3).toString());
                    TFEstado.setText(model.getValueAt(i, 4).toString());                    
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        TFID = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        TFFecha = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        TFArticulo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        TFTalla = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        TFEstado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        statusText = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jTFBuscarPedidos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBCerrar = new javax.swing.JButton();
        jLMover = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(968, 411));
        setMinimumSize(new java.awt.Dimension(968, 411));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(968, 411));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        jLabel2.setFocusable(false);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 130, 20, 22);

        TFID.setEditable(false);
        TFID.setBackground(new java.awt.Color(204, 204, 204));
        TFID.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TFID.setForeground(new java.awt.Color(255, 255, 255));
        TFID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TFID.setBorder(null);
        TFID.setCaretColor(new java.awt.Color(255, 255, 255));
        TFID.setFocusable(false);
        TFID.setOpaque(false);
        getContentPane().add(TFID);
        TFID.setBounds(120, 130, 160, 20);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(30, 150, 270, 10);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha");
        jLabel3.setFocusable(false);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 170, 45, 22);

        TFFecha.setEditable(false);
        TFFecha.setBackground(new java.awt.Color(204, 204, 204));
        TFFecha.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        TFFecha.setForeground(new java.awt.Color(255, 255, 255));
        TFFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TFFecha.setBorder(null);
        TFFecha.setCaretColor(new java.awt.Color(255, 255, 255));
        TFFecha.setFocusable(false);
        TFFecha.setOpaque(false);
        getContentPane().add(TFFecha);
        TFFecha.setBounds(120, 170, 160, 20);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(30, 190, 270, 10);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Articulo");
        jLabel4.setFocusable(false);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 210, 100, 22);

        TFArticulo.setEditable(false);
        TFArticulo.setBackground(new java.awt.Color(204, 204, 204));
        TFArticulo.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        TFArticulo.setForeground(new java.awt.Color(255, 255, 255));
        TFArticulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TFArticulo.setBorder(null);
        TFArticulo.setCaretColor(new java.awt.Color(255, 255, 255));
        TFArticulo.setFocusable(false);
        TFArticulo.setOpaque(false);
        getContentPane().add(TFArticulo);
        TFArticulo.setBounds(120, 210, 160, 20);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 230, 270, 10);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Talla");
        jLabel5.setFocusable(false);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 250, 70, 22);

        TFTalla.setEditable(false);
        TFTalla.setBackground(new java.awt.Color(204, 204, 204));
        TFTalla.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TFTalla.setForeground(new java.awt.Color(255, 255, 255));
        TFTalla.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TFTalla.setBorder(null);
        TFTalla.setCaretColor(new java.awt.Color(255, 255, 255));
        TFTalla.setFocusable(false);
        TFTalla.setOpaque(false);
        getContentPane().add(TFTalla);
        TFTalla.setBounds(120, 250, 160, 20);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(30, 270, 270, 10);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pedidos");
        jLabel8.setFocusable(false);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 20, 170, 30);

        TFEstado.setEditable(false);
        TFEstado.setBackground(new java.awt.Color(204, 204, 204));
        TFEstado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TFEstado.setForeground(new java.awt.Color(255, 255, 255));
        TFEstado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TFEstado.setBorder(null);
        TFEstado.setCaretColor(new java.awt.Color(255, 255, 255));
        TFEstado.setFocusable(false);
        TFEstado.setOpaque(false);
        getContentPane().add(TFEstado);
        TFEstado.setBounds(120, 290, 160, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Estado");
        jLabel6.setFocusable(false);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 290, 60, 22);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(30, 310, 270, 10);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/edit_button.png"))); // NOI18N
        jButton1.setText("Estado = Recibido");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.setMinimumSize(new java.awt.Dimension(96, 40));
        jButton1.setPreferredSize(new java.awt.Dimension(77, 23));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/edit_button_orange.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 340, 180, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/buscar_iconx24.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(150, 70, 40, 40);
        getContentPane().add(statusText);
        statusText.setBounds(310, 350, 20, 24);
        getContentPane().add(jSeparator8);
        jSeparator8.setBounds(180, 100, 120, 10);

        jTFBuscarPedidos.setBackground(new java.awt.Color(204, 204, 204));
        jTFBuscarPedidos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTFBuscarPedidos.setForeground(new java.awt.Color(255, 255, 255));
        jTFBuscarPedidos.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTFBuscarPedidos.setBorder(null);
        jTFBuscarPedidos.setCaretColor(new java.awt.Color(255, 255, 255));
        jTFBuscarPedidos.setName("Buscar"); // NOI18N
        jTFBuscarPedidos.setOpaque(false);
        jTFBuscarPedidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFBuscarPedidosKeyReleased(evt);
            }
        });
        getContentPane().add(jTFBuscarPedidos);
        jTFBuscarPedidos.setBounds(180, 80, 120, 19);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "Articulo", "Talla", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoscrolls(false);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setMaximumSize(new java.awt.Dimension(520, 0));
        jTable1.setOpaque(false);
        jTable1.setRowHeight(30);
        jTable1.setRowMargin(10);
        jTable1.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jTable1.setShowVerticalLines(false);
        jTable1.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(330, 40, 610, 330);

        jBCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jBCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icon_exit.png"))); // NOI18N
        jBCerrar.setBorder(null);
        jBCerrar.setBorderPainted(false);
        jBCerrar.setContentAreaFilled(false);
        jBCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBCerrar.setFocusable(false);
        jBCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jBCerrar);
        jBCerrar.setBounds(950, 0, 20, 20);

        jLMover.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jLMover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLMoverMouseDragged(evt);
            }
        });
        jLMover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLMoverMousePressed(evt);
            }
        });
        getContentPane().add(jLMover);
        jLMover.setBounds(0, 0, 950, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/tab_fondo2.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(483, 284));
        jLabel1.setMinimumSize(new java.awt.Dimension(483, 284));
        jLabel1.setPreferredSize(new java.awt.Dimension(483, 284));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 980, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //BOTÓN EDITAR
        if (TFID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No ha seleccionado ningún pedido", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            if (TFEstado.getText().equalsIgnoreCase("Recibido")) {
                JOptionPane.showMessageDialog(null, "Este pedido ya se ha recibido", "", JOptionPane.ERROR_MESSAGE);                                
            }else{
            int resp = JOptionPane.showConfirmDialog(null, "¿Desea actualizar el estado del pedido seleccionado?", "Confirmar acción", JOptionPane.YES_NO_OPTION);
            if (resp == JOptionPane.YES_OPTION) {
                String vEstado = "Recibido";
                int vId = Integer.parseInt(TFID.getText());

                //REALIZA UPDATE EN LA BASE DE DATOS
                try {
                    PreparedStatement ps = conex.prepareStatement("UPDATE pedidos SET estado='" + vEstado + "' WHERE id=" + vId);
                    ps.executeUpdate();
                } catch (SQLException ex) {
                    Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
                }

                //PRIMERO BORRAR TABLA PARA NO REPETIR DATOS CUANDO HAGA UPDATE
                if (model.getRowCount() > 0) {
                    for (int i = model.getRowCount() - 1; i > -1; i--) {
                        model.removeRow(i);
                    }
                }

                try {
                    //UPDATE EN TABLA
                    updatePedidos();
                } catch (SQLException ex) {
                    Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(null, "Pedido recibido. Stock aumentado.", "Información", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarActionPerformed
        //BOTÓN X, CERRAR VENTANA INDIVIDUAL
        this.dispose();
    }//GEN-LAST:event_jBCerrarActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        //EVENTO CUANDO ENTRA EL RATÓN SOBRE EL BOTÓN EDITAR
        jButton1.setForeground(Color.orange);       
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        //EVENTO CUANDO SALE EL RATÓN DEL BOTÓN EDITAR
        jButton1.setForeground(Color.white);
    }//GEN-LAST:event_jButton1MouseExited

    private void jTFBuscarPedidosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFBuscarPedidosKeyReleased
        //jTextField BÚSQUEDA Pedidos
        String query = jTFBuscarPedidos.getText().toLowerCase();

        filtro(query);
    }//GEN-LAST:event_jTFBuscarPedidosKeyReleased

    private void jLMoverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMoverMouseDragged
        //EVENTO RATÓN ARRASTRAR (Drag)
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jLMoverMouseDragged

    private void jLMoverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMoverMousePressed
        //EVENTO RATÓN PULSADO (Press)
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLMoverMousePressed

    public String getValorTalla(int cod){
        String valor = null;
        
        try {                        
            Statement s3 = conex.createStatement(); 
            String queryNombre = "SELECT valor_talla FROM tallas WHERE id='" + cod +"'";
            ResultSet r3 = s3.executeQuery(queryNombre);
            r3.first();
            valor = r3.getString("valor_talla");           
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }
         return valor;
        
    }
    
    public String getNombreArticulo(int cod) {
        String nom = null;
        
        try {                        
            Statement s3 = conex.createStatement(); 
            String queryNombre = "SELECT nombre FROM articulos WHERE id='" + cod +"'";
            ResultSet r3 = s3.executeQuery(queryNombre);
            r3.first();
            nom = r3.getString("nombre");           
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }
         return nom;
    }
    
    private void updatePedidos() throws SQLException, ClassNotFoundException{
        Connection con = new ConexionDB().getCon();
        
        String query = "SELECT * FROM pedidos";
        PreparedStatement ps = con.prepareStatement(query);
        ResultSet rs = ps.executeQuery();
        
        Object datosFila[] = new Object[5];

        while(rs.next()) {
            datosFila[0] = rs.getInt("id");
            datosFila[1] = rs.getString("fecha");
            datosFila[2] = getNombreArticulo(rs.getInt("articulo"));
            datosFila[3] = getValorTalla(rs.getInt("talla"));
            datosFila[4] = rs.getString("estado");

            model.addRow(datosFila); //TABLA PEDIDOS
        }        
        con.close();        
    }
    
    //MÉTODO FILTRAR RESULTADOS
    private void filtro(String query) { //FILTRO PARA CLIENTES

        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(model);
        jTable1.setRowSorter(tr);

        tr.setRowFilter(RowFilter.regexFilter("(?i)" + query));

        jTable1.getSelectionModel().addListSelectionListener(
                new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                viewRow = jTable1.getSelectedRow();
                if (viewRow < 0) {
                    //Selection got filtered away.
                    statusText.setText("");
                } else {
                    modelRow
                            = jTable1.convertRowIndexToModel(viewRow);
                    statusText.setText(
                            String.format("Selected Row in view: %d. "
                                    + "Selected Row in model: %d.",
                                    viewRow, modelRow));
                }
            }
        }
        );
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Pedidos().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFArticulo;
    private javax.swing.JTextField TFEstado;
    private javax.swing.JTextField TFFecha;
    private javax.swing.JTextField TFID;
    private javax.swing.JTextField TFTalla;
    private javax.swing.JButton jBCerrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLMover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTFBuscarPedidos;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField statusText;
    // End of variables declaration//GEN-END:variables
}
