package modelo;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import utilidades.ConexionDB;

/**
 *
 * @author Quique
 */
public class Articulos extends javax.swing.JFrame {
    
    static ArrayList<Articulo> array_articulos = new ArrayList<>(); //CREO UN ARRAYLIST DE TIPO ARTICULO PARA ALMACENAR TODOS LOS ARTICULOS
   
    Connection conex = new ConexionDB().getCon(); //OBTENGO LA CONEXION QUE CREO EN OTRO PAQUETE
    
    static Articulos articulos;
    
    Statement s;
    ResultSet rs;

    /**
     * Creates new form Articulos
     */
    public Articulos() throws SQLException, ClassNotFoundException {
        initComponents();        
        this.setLocationRelativeTo(null);        
        jTextField1.setVisible(false);
        jButton8.setVisible(false);
        jButton9.setVisible(false);         
        
        
        s = conex.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        String query = "SELECT * FROM articulos";
        rs = s.executeQuery(query);
                
        while (rs.next()) { //CREO NUEVOS OBJETOS TIPO ARTICULO Y LLENO EL ARRAYLIST MIENTRAS TENGA RESULTSET
            int id = rs.getInt("id");
            String nombre = rs.getString("nombre");
            String descripcion = rs.getString("descripcion");
            float precio = Float.parseFloat(rs.getString("precio"));
            int categoria = Integer.parseInt(rs.getString("categoria"));            
            int marca= Integer.parseInt(rs.getString("marca"));                        
            int existencias = Integer.parseInt(rs.getString("existencias"));
            
            array_articulos.add(new Articulo(id, nombre, descripcion, precio, categoria, marca, existencias));            
        }       
        
        /*for (Articulo o : array_articulos) { //RECORRER ARRAY PARA COMPROBAR SI RECOGE OBJETOS
            jTextField1.setText(String.valueOf(o.getId())); //PARSE DE INT A STRING, CON String.valueOf(int);
            jTextField2.setText(o.getNombre());
            jTextField3.setText(o.getDescripcion());
            jTextField4.setText(String.valueOf(o.getPrecio()));
            jTextField5.setText(getNombreCateg(o.getCategoria()));
            jTextField6.setText(getNombreMarca(o.getMarca()));
            jTextField7.setText(String.valueOf(o.getExistencias()));     
        } */         
        
        añadirFilasTabla(); //MÉTODO QUE LLENA LA TABLA CON LA INFO DEL ARRAYLIST
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(860, 485));
        setMinimumSize(new java.awt.Dimension(852, 479));
        setResizable(false);
        setSize(new java.awt.Dimension(850, 480));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        jLabel2.setFocusable(false);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(49, 107, 63, 22);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descripción");
        jLabel3.setFocusable(false);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(49, 148, 91, 22);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Precio");
        jLabel4.setFocusable(false);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(49, 189, 49, 22);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Categoria");
        jLabel5.setFocusable(false);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(49, 230, 76, 22);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Marca");
        jLabel6.setFocusable(false);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(49, 271, 50, 22);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Existencias");
        jLabel7.setFocusable(false);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(49, 312, 85, 22);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Artículos");
        jLabel8.setFocusable(false);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 20, 150, 30);

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setEnabled(false);
        jTextField1.setFocusable(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(170, 80, 39, 24);

        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(null);
        jTextField2.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField2.setOpaque(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(170, 110, 142, 20);

        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setBorder(null);
        jTextField3.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField3.setOpaque(false);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(170, 150, 142, 20);

        jTextField4.setBackground(new java.awt.Color(204, 204, 204));
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setBorder(null);
        jTextField4.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField4.setOpaque(false);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(170, 190, 142, 20);

        jTextField5.setBackground(new java.awt.Color(204, 204, 204));
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setBorder(null);
        jTextField5.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField5.setOpaque(false);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(170, 230, 142, 20);

        jTextField6.setBackground(new java.awt.Color(204, 204, 204));
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setBorder(null);
        jTextField6.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField6.setOpaque(false);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(170, 270, 142, 20);

        jTextField7.setBackground(new java.awt.Color(204, 204, 204));
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setBorder(null);
        jTextField7.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField7.setOpaque(false);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(170, 310, 142, 20);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton5.setText("Añadir");
        jButton5.setFocusable(false);
        jButton5.setPreferredSize(new java.awt.Dimension(77, 23));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(30, 370, 85, 23);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton6.setText("Editar");
        jButton6.setFocusable(false);
        jButton6.setPreferredSize(new java.awt.Dimension(77, 23));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(130, 370, 80, 23);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton7.setText("Borrar");
        jButton7.setFocusable(false);
        jButton7.setPreferredSize(new java.awt.Dimension(77, 23));
        getContentPane().add(jButton7);
        jButton7.setBounds(220, 370, 77, 23);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton8.setText("Aceptar");
        jButton8.setFocusable(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(60, 410, 80, 29);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton9.setText("Cancelar");
        jButton9.setFocusable(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(160, 410, 90, 29);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(50, 330, 240, 10);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(50, 130, 240, 10);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(50, 170, 240, 10);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(50, 210, 240, 10);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(50, 250, 240, 10);
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(50, 290, 240, 10);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Descripcion", "Precio", "Categoria", "Marca", "Existencias"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoscrolls(false);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setMaximumSize(new java.awt.Dimension(520, 0));
        jTable1.setOpaque(false);
        jTable1.setRowHeight(20);
        jTable1.setRowMargin(10);
        jTable1.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(330, 20, 500, 420);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/menu_fondo1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 850, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //BOTÓN AÑADIR 
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");         
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jButton7.setEnabled(false);
        jButton8.setVisible(true);
        jButton9.setVisible(true); 

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       //BOTÓN EDITAR
        /**try{
            String vNombre, vDescripcion, cat, mar;
            int vId, vMarca, vExistencias, vCategoria;
            float vPrecio;            
           
            vId = Integer.parseInt(jTextField1.getText());
            vNombre = jTextField2.getText();
            vDescripcion = jTextField3.getText();
            vPrecio = Float.parseFloat(jTextField4.getText());
           
            vCategoria = getCodigoCateg(cat);
            
            vMarca = getCodigoMarca(mar);            
            vExistencias = Integer.parseInt(jTextField7.getText());
            
            String url = "jdbc:mysql://localhost:3306/clothy";
            String user = "root";
            String pass = "123";
            Connection connection = DriverManager.getConnection(url, user, pass);
            Statement st = connection.createStatement();         
         
            String query = "update articulos set nombre='" + vNombre + "', descripcion='" + vDescripcion + "', precio=" + vPrecio + ", categoria=" + vCategoria + ", marca=" + vMarca + ", existencias=" + vExistencias + " WHERE id=" + vId;
            connection.createStatement();
            st.executeUpdate(query);
            rs.refreshRow();
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //BOTÓN CANCELAR
        jButton8.setVisible(false);
        jButton9.setVisible(false);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //BOTÓN ACEPTAR
       /* try {            
            String vNombre, vDescripcion, cat, mar;
            int vMarca, vExistencias, vCategoria;
            float vPrecio; 
            
            vNombre = jTextField2.getText();
            System.out.println(jTextField2.getText());
            vDescripcion = jTextField3.getText();            
            vPrecio = Float.parseFloat(jTextField4.getText());     
            cat = (String) jCBCategoria.getSelectedItem();
            vCategoria = getCodigoCateg(cat);   
            mar = (String) jCBMarca.getSelectedItem();
            vMarca = getCodigoMarca(mar);  
            vExistencias = Integer.parseInt(jTextField7.getText());  
           
            //Connection con = new ConexionDB().getCon();                
            PreparedStatement ps = conex.prepareStatement("INSERT INTO articulos (nombre, descripcion, precio, categoria, marca, existencias) VALUES (?,?,?,?,?,?)");
            ps.setString(1, vNombre);
            ps.setString(2, vDescripcion);
            ps.setFloat(3, vPrecio);
            ps.setInt(4, vCategoria);
            ps.setInt(5, vMarca);
            ps.setInt(6, vExistencias);
            ps.executeUpdate();           
            
            jButton1.setEnabled(true);
            jButton2.setEnabled(true);
            jButton3.setEnabled(true);
            jButton4.setEnabled(true);
            jButton5.setEnabled(true);
            jButton6.setEnabled(true);
            jButton7.setEnabled(true);
            jButton8.setVisible(false);
            jButton9.setVisible(false);
            
            s = conex.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String query = "SELECT * FROM articulos";
            rs = s.executeQuery(query);
            //estadoInicial();           

        } catch (Exception e) {
            e.printStackTrace();
        }*/
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    articulos =  new Articulos();
                    articulos.setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }
           
    //MÉTODO QUE DEVUELVE EL NOMBRE DE LA TALLA, PASANDO POR PARÁMETRO SU INT
    public static String getNombreCateg(int num) {
        String categ = "";
        
        if (num == 1) categ = "Camisas";
        if (num == 2) categ = "Polos";
        if (num == 3) categ = "Camisetas";
        if (num == 4) categ = "Chaquetas";
        if (num == 5) categ = "Trajes";
        if (num == 6) categ = "Jeans";
        if (num == 7) categ = "Bermudas";
        if (num == 8) categ = "Bañadores";
        if (num == 9) categ = "Zapatos";
        if (num == 10) categ = "Deportes";
        
        return categ;        
        
        /*try {
             
            String url = "jdbc:mysql://localhost:3306/clothy";
            String user = "root";
            String pass = "123";
            Connection connection = DriverManager.getConnection(url, user,pass);
            Statement s3 = connection.createStatement(); 
            String queryNombre = "select nombre from categorias WHERE id=" + num;
            ResultSet r3 = s3.executeQuery(queryNombre);
            r3.first();
            categ = r3.getString("nombre");           
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }   */       
    }
    
    //MÉTODO QUE DEVUELVE EL NÚMERO  DE LA MARCA, PASANDO POR PARÁMETRO SU NOMBRE, (MÉTODO PARA INSERT)
    public static int getCodigoCateg(String nom) {
        int numCateg = 0;
        
         try {
            ResultSet r3;
            String url = "jdbc:mysql://localhost:3306/clothy";
            String user = "root";
            String pass = "123";
            Connection connection = DriverManager.getConnection(url, user,pass);            
            Statement s3 = connection.createStatement(); 
            String queryNombre = "select id from categorias WHERE nombre='" + nom +"'";
            r3 = s3.executeQuery(queryNombre);
            r3.first();
            numCateg = r3.getInt("id");             
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return numCateg;         
   
    }
    
     //MÉTODO QUE DEVUELVE EL NOMBRE DE LA MARCA, PASANDO POR PARÁMETRO SU INT
    public static String getNombreMarca(int num) {
        String marca = "";
        
        if (num == 1) marca = "Ralph Lauren";
        if (num == 2) marca = "Valentino";
        if (num == 3) marca = "Lacoste";
        if (num == 4) marca = "Gucci";
        if (num == 5) marca = "Prada";
        if (num == 6) marca = "Tommy Hilfiger";
        if (num == 7) marca = "Emporio Armani";
        if (num == 8) marca = "Hugo Boss";
        if (num == 9) marca = "Pepe Jeans";
        if (num == 10) marca = "Levis";
        
        return marca;
        
        /*try {
            ResultSet r3; 
            String url = "jdbc:mysql://localhost:3306/clothy";
            String user = "root";
            String pass = "123";
            Connection connection = DriverManager.getConnection(url, user,pass);
            Statement s3 = connection.createStatement(); 
            String queryNombre = "select nombre from marcas WHERE id=" + num;
            r3 = s3.executeQuery(queryNombre);
            r3.first();
            marca = r3.getString("nombre");           
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }       */         
        
    }
    
    //MÉTODO QUE DEVUELVE EL NÚMERO  DE LA MARCA, PASANDO POR PARÁMETRO SU NOMBRE, (MÉTODO PARA INSERT)
    public static int getCodigoMarca(String nom) {
        int numMarca = 0;
        
         try {
            ResultSet r3;
            String url = "jdbc:mysql://localhost:3306/clothy";
            String user = "root";
            String pass = "123";
            Connection connection = DriverManager.getConnection(url, user,pass);            
            Statement s3 = connection.createStatement(); 
            String queryNombre = "select id from marcas WHERE nombre='" + nom +"'";
            r3 = s3.executeQuery(queryNombre);
            r3.first();
            numMarca = r3.getInt("id");           
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }     
   
        return numMarca;
    }
    
    public void añadirFilasTabla(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        Object datosFila []= new Object [7]; //EL RANGO DEL ARRAY REPRESENTA LAS COLUMNAS DE LA TABLA, EN ESTE CASO 7
        
        for (int i = 0; i < array_articulos.size(); i++) {
            datosFila[0] = array_articulos.get(i).getId();
            datosFila[1] = array_articulos.get(i).getNombre();
            datosFila[2] = array_articulos.get(i).getDescripcion();
            datosFila[3] = array_articulos.get(i).getPrecio();
            datosFila[4] = array_articulos.get(i).getCategoria();
            datosFila[5] = array_articulos.get(i).getMarca();
            datosFila[6] = array_articulos.get(i).getExistencias();

            model.addRow(datosFila);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
