package vista;

import modelo.Empleado;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import utilidades.*;
import javax.swing.JOptionPane;
import static vista.Menu.menu;

/**
 *
 * @author Quique
 */
public class Login extends javax.swing.JFrame {
    
    ArrayList<Empleado> empleados;   
    static Login login;
    static String user_actual;    
    
    int x, y; //VARIABLES USADAS PARA EL MARCO DEL FRAME, PARA MOVERLO
    
    
    /**
     * Creates new form Login
     * @throws java.sql.SQLException
     */
    public Login() throws SQLException {        
        initComponents();         
        //AWTUtilities.setWindowOpaque(this, false);//PARA EL MARCO MOVER FRAME
        this.setLocationRelativeTo(null); //PARA CENTRAR FRAME EN PANTALLA
        empleados = utilidades.ConexionDB.empleados(); //arrayList con los empleados     

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo = new javax.swing.JLabel();
        jLUsuario = new javax.swing.JLabel();
        jLPass = new javax.swing.JLabel();
        jTFUsuario = new javax.swing.JTextField();
        user_icon = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPFPass = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jBLogin = new javax.swing.JButton();
        jBCerrar = new javax.swing.JButton();
        jLMover = new javax.swing.JLabel();
        pass_icon = new javax.swing.JLabel();
        jLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(485, 600));
        setMinimumSize(new java.awt.Dimension(485, 600));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(485, 600));
        getContentPane().setLayout(null);

        jLTitulo.setFont(new java.awt.Font("Magneto", 2, 48)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLTitulo.setText("Clothy");
        getContentPane().add(jLTitulo);
        jLTitulo.setBounds(260, 70, 170, 80);

        jLUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLUsuario.setText("Usuario");
        getContentPane().add(jLUsuario);
        jLUsuario.setBounds(280, 290, 120, 20);

        jLPass.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLPass.setForeground(new java.awt.Color(255, 255, 255));
        jLPass.setText("Contraseña");
        getContentPane().add(jLPass);
        jLPass.setBounds(280, 380, 150, 30);

        jTFUsuario.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTFUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jTFUsuario.setBorder(null);
        jTFUsuario.setCaretColor(new java.awt.Color(255, 255, 255));
        jTFUsuario.setOpaque(false);
        getContentPane().add(jTFUsuario);
        jTFUsuario.setBounds(280, 330, 110, 20);

        user_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/userx24.png"))); // NOI18N
        getContentPane().add(user_icon);
        user_icon.setBounds(390, 320, 30, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(280, 350, 110, 10);

        jPFPass.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPFPass.setForeground(new java.awt.Color(255, 255, 255));
        jPFPass.setBorder(null);
        jPFPass.setCaretColor(new java.awt.Color(255, 255, 255));
        jPFPass.setOpaque(false);
        getContentPane().add(jPFPass);
        jPFPass.setBounds(280, 430, 100, 20);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(280, 450, 110, 10);

        jBLogin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBLogin.setText("Login");
        jBLogin.setBorderPainted(false);
        jBLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jBLogin);
        jBLogin.setBounds(270, 480, 150, 45);

        jBCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jBCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icon_exit.png"))); // NOI18N
        jBCerrar.setBorder(null);
        jBCerrar.setBorderPainted(false);
        jBCerrar.setContentAreaFilled(false);
        jBCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBCerrar.setFocusable(false);
        jBCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jBCerrar);
        jBCerrar.setBounds(462, 0, 30, 20);

        jLMover.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jLMover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLMoverMouseDragged(evt);
            }
        });
        jLMover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLMoverMousePressed(evt);
            }
        });
        getContentPane().add(jLMover);
        jLMover.setBounds(0, 0, 470, 30);

        pass_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/pass_icon.png"))); // NOI18N
        getContentPane().add(pass_icon);
        pass_icon.setBounds(390, 420, 30, 30);

        jLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/fondoLogin.png"))); // NOI18N
        getContentPane().add(jLFondo);
        jLFondo.setBounds(0, 0, 485, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //BOTÓN CERRAR LOGIN
    private void jBCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarActionPerformed
        //CONFIRMAR CERRAR PROGRAMA
        int resp = JOptionPane.showConfirmDialog(null, "¿Salir del programa?", "Confirmar acción", JOptionPane.YES_NO_OPTION);
           if (resp == JOptionPane.YES_OPTION) {
               System.exit(0);               
           } else{
               
           }                
    }//GEN-LAST:event_jBCerrarActionPerformed

    
    //BOTÓN LOGIN
    private void jBLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLoginActionPerformed

        String user = jTFUsuario.getText();
        String pass = jPFPass.getText();
        boolean isUser = false;
        boolean isAdmin = false;

        for (Empleado emp : empleados) { //BUCLE FOR EACH PARA RECORRER ARRAY DE EMPLEADOS

            String userAc = emp.getId_login();

            if (user.equalsIgnoreCase(userAc) && pass.equalsIgnoreCase(emp.getPassword())) {
                isUser = true;            
                user_actual = user;                
            }
        }

        if (isUser == true) {
            try {
                menu = new Menu();
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
            //HACEMOS VISIBLE EL MENU
            menu.setVisible(true); 
            //RESET CAMPOS LOGIN
            jTFUsuario.setText("");     
            jPFPass.setText("");
            //OCULTAMOS LOGIN
            login.setVisible(false);
        } else {
            //MENSAJE ERROR USER Y PASS
            JOptionPane.showMessageDialog(null,"Usuario o contraseña no válidos", "Error", JOptionPane.ERROR_MESSAGE);            
        }
    }//GEN-LAST:event_jBLoginActionPerformed

    private void jLMoverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMoverMousePressed
        //EVENTO RATÓN PULSADO (Press)
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLMoverMousePressed

    private void jLMoverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMoverMouseDragged
        //EVENTO RATÓN ARRASTRAR (Drag)
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jLMoverMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                //Establecer conexión con la DataBase
                try {
                    
                    new ConexionDB(); 
                    
                } catch (Exception e) {
                    e.printStackTrace();
                } 
                
                try {
                    
                   login = new Login();
                   login.setVisible(true);
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }                
                              
            }
        });
    }  

    public static String getUser_actual() {
        return user_actual;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCerrar;
    private javax.swing.JButton jBLogin;
    private javax.swing.JLabel jLFondo;
    private javax.swing.JLabel jLMover;
    private javax.swing.JLabel jLPass;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JPasswordField jPFPass;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTFUsuario;
    private javax.swing.JLabel pass_icon;
    private javax.swing.JLabel user_icon;
    // End of variables declaration//GEN-END:variables
}
