package vista;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static vista.Login.*;



/**
 *
 * @author Quique
 */
public class Menu extends javax.swing.JFrame {    
    
    static Menu menu;    

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        user_logeado.setText(user_actual);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        user_logeado = new javax.swing.JLabel();
        jBArticulos = new javax.swing.JButton();
        jBCategorias = new javax.swing.JButton();
        jBMarcas = new javax.swing.JButton();
        jBTallas = new javax.swing.JButton();
        jBLineas_venta = new javax.swing.JButton();
        jBEmpleados = new javax.swing.JButton();
        jBClientes = new javax.swing.JButton();
        jBVentas = new javax.swing.JButton();
        jBSesion = new javax.swing.JButton();
        jLArticulos = new javax.swing.JLabel();
        jLCategorias = new javax.swing.JLabel();
        jLMarcas = new javax.swing.JLabel();
        jLTallas = new javax.swing.JLabel();
        jLLineas_venta = new javax.swing.JLabel();
        jLEmpleados = new javax.swing.JLabel();
        jLClientes = new javax.swing.JLabel();
        jLVentas = new javax.swing.JLabel();
        jBPedidos = new javax.swing.JButton();
        jLPedidos = new javax.swing.JLabel();
        jBCerrar = new javax.swing.JButton();
        fondo_menu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(725, 365));
        setMinimumSize(new java.awt.Dimension(725, 365));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(725, 365));
        setResizable(false);
        setSize(new java.awt.Dimension(725, 365));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tekton Pro", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario_");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 110, 48);

        user_logeado.setFont(new java.awt.Font("Tekton Pro", 0, 32)); // NOI18N
        user_logeado.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(user_logeado);
        user_logeado.setBounds(120, 0, 115, 48);

        jBArticulos.setIcon(new javax.swing.ImageIcon("C:\\Users\\Quique\\Documents\\1DAW\\EntornosDesarrollo\\Clothy-app\\images\\articulos_icon.png")); // NOI18N
        jBArticulos.setToolTipText("");
        getContentPane().add(jBArticulos);
        jBArticulos.setBounds(60, 90, 101, 78);

        jBCategorias.setIcon(new javax.swing.ImageIcon("C:\\Users\\Quique\\Documents\\1DAW\\EntornosDesarrollo\\Clothy-app\\images\\categorias_icon.png")); // NOI18N
        jBCategorias.setToolTipText("");
        getContentPane().add(jBCategorias);
        jBCategorias.setBounds(190, 90, 101, 78);

        jBMarcas.setIcon(new javax.swing.ImageIcon("C:\\Users\\Quique\\Documents\\1DAW\\EntornosDesarrollo\\Clothy-app\\images\\marcas_icon.png")); // NOI18N
        jBMarcas.setToolTipText("");
        getContentPane().add(jBMarcas);
        jBMarcas.setBounds(320, 90, 101, 78);

        jBTallas.setIcon(new javax.swing.ImageIcon("C:\\Users\\Quique\\Documents\\1DAW\\EntornosDesarrollo\\Clothy-app\\images\\tallas_icon.png")); // NOI18N
        jBTallas.setToolTipText("");
        getContentPane().add(jBTallas);
        jBTallas.setBounds(450, 90, 101, 78);

        jBLineas_venta.setIcon(new javax.swing.ImageIcon("C:\\Users\\Quique\\Documents\\1DAW\\EntornosDesarrollo\\Clothy-app\\images\\lineas_venta_icon.png")); // NOI18N
        jBLineas_venta.setToolTipText("");
        getContentPane().add(jBLineas_venta);
        jBLineas_venta.setBounds(580, 90, 101, 78);

        jBEmpleados.setIcon(new javax.swing.ImageIcon("C:\\Users\\Quique\\Documents\\1DAW\\EntornosDesarrollo\\Clothy-app\\images\\empleados_icon2.png")); // NOI18N
        jBEmpleados.setToolTipText("");
        getContentPane().add(jBEmpleados);
        jBEmpleados.setBounds(60, 220, 101, 78);

        jBClientes.setIcon(new javax.swing.ImageIcon("C:\\Users\\Quique\\Documents\\1DAW\\EntornosDesarrollo\\Clothy-app\\images\\clientes_icon.png")); // NOI18N
        jBClientes.setToolTipText("");
        getContentPane().add(jBClientes);
        jBClientes.setBounds(190, 220, 101, 78);

        jBVentas.setIcon(new javax.swing.ImageIcon("C:\\Users\\Quique\\Documents\\1DAW\\EntornosDesarrollo\\Clothy-app\\images\\ventas_icon.png")); // NOI18N
        jBVentas.setToolTipText("");
        getContentPane().add(jBVentas);
        jBVentas.setBounds(320, 220, 101, 78);

        jBSesion.setFont(new java.awt.Font("Magneto", 0, 14)); // NOI18N
        jBSesion.setIcon(new javax.swing.ImageIcon("C:\\Users\\Quique\\Documents\\1DAW\\EntornosDesarrollo\\Clothy-app\\images\\logout.png")); // NOI18N
        jBSesion.setToolTipText("Cierra sesión");
        jBSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSesionActionPerformed(evt);
            }
        });
        getContentPane().add(jBSesion);
        jBSesion.setBounds(680, 320, 30, 30);

        jLArticulos.setFont(new java.awt.Font("Magneto", 0, 18)); // NOI18N
        jLArticulos.setForeground(new java.awt.Color(255, 255, 255));
        jLArticulos.setText("Artículos");
        jLArticulos.setToolTipText("");
        getContentPane().add(jLArticulos);
        jLArticulos.setBounds(60, 170, 101, 26);

        jLCategorias.setFont(new java.awt.Font("Magneto", 0, 18)); // NOI18N
        jLCategorias.setForeground(new java.awt.Color(255, 255, 255));
        jLCategorias.setText("Categorias");
        jLCategorias.setToolTipText("");
        getContentPane().add(jLCategorias);
        jLCategorias.setBounds(180, 170, 104, 26);

        jLMarcas.setFont(new java.awt.Font("Magneto", 0, 18)); // NOI18N
        jLMarcas.setForeground(new java.awt.Color(255, 255, 255));
        jLMarcas.setText("Marcas");
        jLMarcas.setToolTipText("");
        getContentPane().add(jLMarcas);
        jLMarcas.setBounds(330, 170, 74, 26);

        jLTallas.setFont(new java.awt.Font("Magneto", 0, 18)); // NOI18N
        jLTallas.setForeground(new java.awt.Color(255, 255, 255));
        jLTallas.setText("Tallas");
        jLTallas.setToolTipText("");
        getContentPane().add(jLTallas);
        jLTallas.setBounds(470, 170, 60, 26);

        jLLineas_venta.setFont(new java.awt.Font("Magneto", 0, 18)); // NOI18N
        jLLineas_venta.setForeground(new java.awt.Color(255, 255, 255));
        jLLineas_venta.setText("Lineas de venta");
        jLLineas_venta.setToolTipText("");
        getContentPane().add(jLLineas_venta);
        jLLineas_venta.setBounds(550, 170, 159, 26);

        jLEmpleados.setFont(new java.awt.Font("Magneto", 0, 18)); // NOI18N
        jLEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        jLEmpleados.setText("Empleados");
        jLEmpleados.setToolTipText("");
        getContentPane().add(jLEmpleados);
        jLEmpleados.setBounds(50, 300, 105, 26);

        jLClientes.setFont(new java.awt.Font("Magneto", 0, 18)); // NOI18N
        jLClientes.setForeground(new java.awt.Color(255, 255, 255));
        jLClientes.setText("Clientes");
        jLClientes.setToolTipText("");
        getContentPane().add(jLClientes);
        jLClientes.setBounds(200, 300, 81, 26);

        jLVentas.setFont(new java.awt.Font("Magneto", 0, 18)); // NOI18N
        jLVentas.setForeground(new java.awt.Color(255, 255, 255));
        jLVentas.setText("Ventas");
        jLVentas.setToolTipText("");
        getContentPane().add(jLVentas);
        jLVentas.setBounds(340, 300, 65, 26);

        jBPedidos.setIcon(new javax.swing.ImageIcon("C:\\Users\\Quique\\Documents\\1DAW\\EntornosDesarrollo\\Clothy-app\\images\\pedidos_icon.png")); // NOI18N
        jBPedidos.setToolTipText("");
        getContentPane().add(jBPedidos);
        jBPedidos.setBounds(450, 220, 101, 78);

        jLPedidos.setFont(new java.awt.Font("Magneto", 0, 18)); // NOI18N
        jLPedidos.setForeground(new java.awt.Color(255, 255, 255));
        jLPedidos.setText("Pedidos");
        jLPedidos.setToolTipText("");
        getContentPane().add(jLPedidos);
        jLPedidos.setBounds(460, 300, 77, 26);

        jBCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/icon_exit.png"))); // NOI18N
        jBCerrar.setBorderPainted(false);
        jBCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jBCerrar);
        jBCerrar.setBounds(690, 10, 20, 20);

        fondo_menu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Quique\\Documents\\1DAW\\EntornosDesarrollo\\Clothy-app\\images\\menu_fondo1.jpg")); // NOI18N
        fondo_menu.setMaximumSize(new java.awt.Dimension(733, 365));
        fondo_menu.setMinimumSize(new java.awt.Dimension(733, 365));
        fondo_menu.setPreferredSize(new java.awt.Dimension(733, 365));
        getContentPane().add(fondo_menu);
        fondo_menu.setBounds(-6, 0, 733, 365);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //BOTÓN CERRAR SESIÓN
    private void jBSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSesionActionPerformed
                
        int resp = JOptionPane.showConfirmDialog(null, "¿Cerrar Sesión?", "Confirmar acción", JOptionPane.YES_NO_OPTION);
        
        if (resp == JOptionPane.YES_OPTION) {
            try {
                login.setVisible(true);
                menu.setVisible(false);

            } catch (Throwable ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {

        }      
    }//GEN-LAST:event_jBSesionActionPerformed

    private void jBCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarActionPerformed
        //CONFIRMAR CERRAR PROGRAMA
        int resp = JOptionPane.showConfirmDialog(null, "¿Salir del programa?", "Confirmar acción", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else{

        }
    }//GEN-LAST:event_jBCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {       
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                menu = new Menu();
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo_menu;
    private javax.swing.JButton jBArticulos;
    private javax.swing.JButton jBCategorias;
    private javax.swing.JButton jBCerrar;
    private javax.swing.JButton jBClientes;
    private javax.swing.JButton jBEmpleados;
    private javax.swing.JButton jBLineas_venta;
    private javax.swing.JButton jBMarcas;
    private javax.swing.JButton jBPedidos;
    private javax.swing.JButton jBSesion;
    private javax.swing.JButton jBTallas;
    private javax.swing.JButton jBVentas;
    private javax.swing.JLabel jLArticulos;
    private javax.swing.JLabel jLCategorias;
    private javax.swing.JLabel jLClientes;
    private javax.swing.JLabel jLEmpleados;
    private javax.swing.JLabel jLLineas_venta;
    private javax.swing.JLabel jLMarcas;
    private javax.swing.JLabel jLPedidos;
    private javax.swing.JLabel jLTallas;
    private javax.swing.JLabel jLVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel user_logeado;
    // End of variables declaration//GEN-END:variables
}
